import { magicLink as magicLinkPlugin } from "better-auth/plugins/magic-link";
import type { Mailer } from "@broberg/mail";

/**
 * Magic-link sign-in, delivered through @broberg/mail (the fleet's Resend
 * primitive) — never a raw provider/SMTP integration. Better Auth's magicLink
 * plugin owns token generation + the sign-in endpoints; this module owns ONLY
 * the `sendMagicLink` delivery callback, routed to the injected Mailer.
 */

export interface MagicLinkConfig {
  /** A @broberg/mail Mailer — magic-link emails route through it (reuse-first).
   *  When the mailer has no API key it ship-darks (logged no-op), so dev never
   *  sends real mail. */
  mailer: Mailer;
  /** Override the From address (else the mailer's configured default). */
  from?: string;
  /** Subject line. Default: "Your sign-in link". */
  subject?: string;
  /** Custom body renderer. Default: a minimal link email. */
  render?: (data: { email: string; url: string }) => { html?: string; text?: string };
  /** Passed through to Better Auth's magicLink plugin (e.g. expiresIn, disableSignUp). */
  options?: Omit<Parameters<typeof magicLinkPlugin>[0], "sendMagicLink">;
}

const DEFAULT_SUBJECT = "Your sign-in link";

/** Minimal default body. The link URL is generated by Better Auth (trusted), not
 *  user input. Consumers override via `render` for branded templates (templates
 *  stay per-app — @broberg/mail owns delivery only). */
function defaultBody(url: string): { html: string; text: string } {
  return {
    text: `Sign in by opening this link:\n\n${url}\n\nIf you didn't request this, you can safely ignore this email.`,
    html:
      `<p>Sign in by clicking the link below:</p>` +
      `<p><a href="${url}">Sign in</a></p>` +
      `<p style="color:#888;font-size:12px">If you didn't request this, you can safely ignore this email.</p>`,
  };
}

/** The `sendMagicLink` callback — exported so the @broberg/mail wiring is unit-
 *  testable without spinning a full request through Better Auth. */
export function makeMagicLinkSender(cfg: MagicLinkConfig) {
  return async (data: { email: string; url: string; token: string }): Promise<void> => {
    const body = cfg.render ? cfg.render(data) : defaultBody(data.url);
    await cfg.mailer.send({
      to: data.email,
      subject: cfg.subject ?? DEFAULT_SUBJECT,
      ...body,
      ...(cfg.from ? { from: cfg.from } : {}),
    });
  };
}

/** Build the Better Auth magicLink plugin with delivery wired to @broberg/mail.
 *  Return type is annotated to Better Auth's own plugin type so the emitted
 *  declarations stay portable (the inferred type otherwise leaks a pnpm-internal
 *  zod path — TS2742). */
export function buildMagicLinkPlugin(cfg: MagicLinkConfig): ReturnType<typeof magicLinkPlugin> {
  return magicLinkPlugin({
    ...cfg.options,
    sendMagicLink: makeMagicLinkSender(cfg),
  });
}
