/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all jobs */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by name, URL, or description */
                    search?: string;
                    tag?: string;
                    status?: "active" | "paused" | "failing";
                    protocol?: "https" | "http" | "wss" | "ws";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of jobs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JobInput"];
                };
            };
            responses: {
                /** @description Created job */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update a job */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JobInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete a job and all its execution history */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lightweight job status for external monitoring
         * @description Curated status (job summary + last execution). Designed for uptime /
         *     monitoring probes. `ok` is true when the last run succeeded or never ran.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobStatus"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger job manually */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Execution"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle job enabled/disabled */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            enabled?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List executions for a job */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    status?: "success" | "failure" | "timeout" | "running";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            executions?: components["schemas"]["Execution"][];
                            total?: number;
                            limit?: number;
                            offset?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List notifications for a job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"][];
                    };
                };
            };
        };
        put?: never;
        /** Add a notification to a job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NotificationInput"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        /** Remove a notification */
        delete: {
            parameters: {
                query: {
                    notifId: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export all jobs as JSON */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobInput"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import jobs from JSON */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JobInput"][];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            imported?: number;
                            errors?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard statistics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            totalJobs?: number;
                            activeJobs?: number;
                            executions24h?: number;
                            /** @description 0-100 */
                            successRate24h?: number;
                            /** @description ms */
                            avgDuration24h?: number;
                            failingJobs?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Execution timeline for chart */
        get: {
            parameters: {
                query?: {
                    period?: "1h" | "6h" | "24h" | "7d" | "30d";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            time?: string;
                            success?: number;
                            failure?: number;
                            total?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/top-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top jobs by execution count */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            name?: string;
                            runs24h?: number;
                            successRate?: number;
                            avgDuration?: number;
                            lastStatus?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated execution log across all jobs */
        get: {
            parameters: {
                query?: {
                    jobId?: string;
                    status?: "success" | "failure" | "timeout";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            executions?: components["schemas"]["ExecutionWithJob"][];
                            total?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all unique tags */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhook/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a job by webhook token (no auth required)
         * @description Each job has a unique, secret webhook token. POST to this URL to trigger
         *     the job immediately. The token is visible in the job detail page.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            executionId?: string;
                            status?: string;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description Job is disabled */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys (preview only — plaintext never stored) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKey"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Mint a new API key
         * @description Returns the plaintext key **once** in the response field `key`.
         *     It is not stored — copy it immediately.
         *
         *     Requires a session **or** an `admin`-scoped token (`canMint`). Pass `scope`
         *     to bind the new token to a repo. Only a session may mint full-access (omit
         *     `scope`) or `admin` tokens; an admin token may only provision repo-scoped tokens.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example xrt81 production */
                        name: string;
                        /**
                         * @description Repo key, e.g. 'xrt81'. Omit for a full-access token (session only).
                         * @example xrt81
                         */
                        scope?: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKey"] & {
                            /**
                             * @description Plaintext key — shown once only
                             * @example cj_abc123...
                             */
                            key?: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update display name */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            name?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                            /** @example ok */
                            db?: string;
                            uptime?: number;
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Job: {
            id?: string;
            name?: string;
            description?: string | null;
            /** @example *\/15 * * * * */
            schedule?: string;
            /** @example Europe/Copenhagen */
            timezone?: string;
            /** @enum {string} */
            protocol?: "https" | "http" | "wss" | "ws";
            /** @enum {string} */
            method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
            /** Format: uri */
            url?: string;
            /** @description JSON string */
            headers?: string | null;
            body?: string | null;
            /** @description ms */
            timeout?: number;
            retryCount?: number;
            /** @description ms */
            retryDelay?: number;
            /** @enum {string} */
            retryStrategy?: "fixed" | "exponential";
            webhookToken?: string;
            enabled?: boolean;
            /** @description Unix ms */
            lastRunAt?: number | null;
            lastRunStatus?: string | null;
            /** @description Unix ms */
            nextRunAt?: number | null;
            createdAt?: number;
            updatedAt?: number;
            /** @description Owner/repo key; null = unowned (legacy/admin space) */
            scope?: string | null;
            /** @description Client idempotency key, unique per scope */
            externalId?: string | null;
        };
        JobInput: {
            name: string;
            description?: string;
            /** @example *\/15 * * * * */
            schedule: string;
            /** @default Europe/Copenhagen */
            timezone: string;
            /** @enum {string} */
            protocol: "https" | "http" | "wss" | "ws";
            /**
             * @default GET
             * @enum {string}
             */
            method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
            /** Format: uri */
            url: string;
            /** @description JSON string of key/value headers */
            headers?: string;
            body?: string;
            /** @default 30000 */
            timeout: number;
            /** @default 0 */
            retryCount: number;
            /** @default 5000 */
            retryDelay: number;
            /**
             * @default fixed
             * @enum {string}
             */
            retryStrategy: "fixed" | "exponential";
            tags?: string[];
            /** @default true */
            enabled: boolean;
            /** @description Idempotency key — POST /api/jobs upserts on (scope, externalId): 200 if it updated an existing job, 201 if created */
            externalId?: string;
        };
        Execution: {
            id?: string;
            jobId?: string;
            /** @description Unix ms */
            startedAt?: number;
            completedAt?: number | null;
            /** @description ms */
            duration?: number | null;
            /** @enum {string} */
            status?: "success" | "failure" | "timeout" | "running" | "skipped";
            statusCode?: number | null;
            /** @description Truncated at 10KB */
            responseBody?: string | null;
            /** @description JSON string */
            responseHeaders?: string | null;
            errorMessage?: string | null;
            retryAttempt?: number;
            /** @enum {string} */
            triggeredBy?: "schedule" | "manual" | "webhook" | "retry";
        };
        ExecutionWithJob: components["schemas"]["Execution"] & {
            jobName?: string;
            jobUrl?: string;
        };
        JobStatus: {
            id?: string;
            name?: string;
            enabled?: boolean;
            schedule?: string;
            timezone?: string;
            url?: string;
            /** @description true if last run succeeded or never ran */
            ok?: boolean;
            lastRunStatus?: string | null;
            /** @description Unix ms */
            lastRunAt?: number | null;
            /** @description Unix ms */
            nextRunAt?: number | null;
            lastExecution?: {
                id?: string;
                /** @enum {string} */
                status?: "success" | "failure" | "timeout" | "running" | "skipped";
                /** @description Unix ms */
                startedAt?: number;
                completedAt?: number | null;
                /** @description ms */
                duration?: number | null;
                statusCode?: number | null;
                errorMessage?: string | null;
                responseBody?: string | null;
                retryAttempt?: number;
                /** @enum {string} */
                triggeredBy?: "schedule" | "manual" | "webhook" | "retry";
            } | null;
        };
        Notification: {
            id?: string;
            jobId?: string;
            /** @enum {string} */
            type?: "email" | "discord" | "webhook";
            /** @description Email address or webhook URL */
            target?: string;
            onSuccess?: boolean;
            onFailure?: boolean;
            onRecovery?: boolean;
        };
        ApiKey: {
            id?: string;
            name?: string;
            /**
             * @description First 8 chars of key for display
             * @example cj_abc123…
             */
            preview?: string;
            /** @description null = full/legacy (no mint), 'admin' = full + mint, '<repo>' = scoped to own jobs */
            scope?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            lastUsedAt?: string | null;
            enabled?: boolean | null;
        };
        NotificationInput: {
            /** @enum {string} */
            type: "email" | "discord" | "webhook";
            target: string;
            /** @default false */
            onSuccess: boolean;
            /** @default true */
            onFailure: boolean;
            /** @default true */
            onRecovery: boolean;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "unauthorized" | "forbidden" | "not_found" | "validation_error" | "invalid_cron";
                message: string;
                /** @description Optional structured detail (e.g. zod flatten output) */
                details?: unknown;
            };
        };
    };
    responses: {
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not permitted (scoped token, or token cannot mint) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
